name: ch4_challenge

on: [push]

env: 
  ARTIFACT_NAME: myartifact

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run python script
      uses: actions/checkout@v2
      run: python hello.py

  build:
    needs: [test]  
    runs-on: ubuntu-latest
    steps:
    - name: Upload the artifact
      uses: actions/checkout@v2
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .